In [2]:
import geonamescache
import pandas as pd

gc = geonamescache.GeonamesCache()
cities = gc.get_cities()

# Normalizzazione in DataFrame
df_cities = pd.DataFrame.from_dict(cities, orient="index")[
    ["name", "countrycode", "latitude", "longitude", "population"]
]
countries = pd.DataFrame.from_dict(gc.get_countries(), orient="index")[
    ["iso", "name"]
].rename(columns={"name": "country_name"})

# Merge per avere il nome esteso del paese
df_mapping = df_cities.merge(
    countries, left_on="countrycode", right_on="iso", how="left"
)

In [3]:
df_cities

                            name countrycode  latitude  longitude  population
3040051             les Escaldes          AD  42.50729    1.53414       15853
3041563         Andorra la Vella          AD  42.50779    1.52109       20430
290503                   Warīsān          AE  25.16744   55.40708      108759
290581                Umm Suqaym          AE  25.15491   55.21015       16459
290594        Umm Al Quwain City          AE  25.56473   55.55517       59098
...                          ...         ...       ...        ...         ...
895061                   Bindura          ZW -17.30192   31.33056       50400
895269                Beitbridge          ZW -22.21667   30.00000       58574
1085510                  Epworth          ZW -17.89000   31.14750      206365
1106542              Chitungwiza          ZW -18.01274   31.07555      371246
13132735  Harare Western Suburbs          ZW -17.84150   30.87674       15556

[34006 rows x 5 columns]

In [4]:
df_mapping

,name,countrycode,latitude,longitude,population,iso,country_name
0,les Escaldes,AD,42.50729,1.53414,15853,AD,Andorra
1,Andorra la Vella,AD,42.50779,1.52109,20430,AD,Andorra
2,Warīsān,AE,25.16744,55.40708,108759,AE,United Arab Emirates
3,Umm Suqaym,AE,25.15491,55.21015,16459,AE,United Arab Emirates
4,Umm Al Quwain City,AE,25.56473,55.55517,59098,AE,United Arab Emirates
...,...,...,...,...,...,...,...
34001,Bindura,ZW,-17.30192,31.33056,50400,ZW,Zimbabwe
34002,Beitbridge,ZW,-22.21667,30.00000,58574,ZW,Zimbabwe
34003,Epworth,ZW,-17.89000,31.14750,206365,ZW,Zimbabwe
34004,Chitungwiza,ZW,-18.01274,31.07555,371246,ZW,Zimbabwe
34005,Harare Western Suburbs,ZW,-17.84150,30.87674,15556,ZW,Zimbabwe